# Nome do Workflow
name: Criador de Repositório

# Gatilho do workflow
on:
  workflow_dispatch:
    inputs:
      repoName:
        description: "Nome do novo repositório (ex: meu-projeto-novo)"
        required: true
        type: string
      repoDescription:
        description: "Descrição breve do repositório"
        required: false
        type: string
      repoTeam:
        description: "Slug do time principal que será dono do repositório (ex: time-desenvolvimento)"
        required: true
        type: string

jobs:
  create-and-configure-repository:
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Gerar um token de curta duração a partir do GitHub App.
      - name: Gerar Token de Autenticação do GitHub App
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      # Passo 2: Executar o script principal usando o token gerado.
      - name: Criar e Configurar Repositório via Script
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            // --- Parâmetros de Entrada e Configurações Fixas ---
            const orgName = context.repo.owner;
            const repoName = "${{ github.event.inputs.repoName }}".trim();
            const repoDescription = "${{ github.event.inputs.repoDescription }}" || `Repositório ${repoName} criado via automação`;
            const mainTeamSlug = "${{ github.event.inputs.repoTeam }}".trim().toLowerCase();
            
            // Repositório e branch de template fixos
            const templateRepo = 'trade-actions';
            const templateBranch = 'stable';
            const defaultBranch = 'main';

            const log = (message) => core.info(message);

            try {
              // --- 1. CRIAR UM REPOSITÓRIO NOVO E VAZIO ---
              log(`Iniciando a criação do repositório "${repoName}"...`);
              const createRepoResponse = await github.rest.repos.createInOrg({
                org: orgName,
                name: repoName,
                description: repoDescription,
                private: true,
                auto_init: true, // Cria o repo com um README para ter o branch 'main'
              });
              const repo = createRepoResponse.data;
              log(`✅ Repositório "${repo.name}" criado com sucesso! URL: ${repo.html_url}`);

              // --- 2. COPIAR ARQUIVOS DO TEMPLATE ---
              log(`Copiando arquivos de "${templateRepo}" (branch: ${templateBranch})...`);
              const pathsToCopy = [".github", "envs-dev.yaml", "envs-hml.yaml", "envs-prd.yaml", "secrets.yaml", "gh-actions-config.yaml"];
              
              const copyContent = async (path) => {
                try {
                  const contentResponse = await github.rest.repos.getContent({
                    owner: orgName,
                    repo: templateRepo,
                    path: path,
                    ref: templateBranch,
                  });

                  if (Array.isArray(contentResponse.data)) { // Se for um diretório
                    for (const item of contentResponse.data) {
                      await copyContent(item.path); // Chama recursivamente para cada item no diretório
                    }
                  } else { // Se for um arquivo
                    log(` -> Copiando arquivo: ${contentResponse.data.path}`);
                    await github.rest.repos.createOrUpdateFileContents({
                      owner: orgName,
                      repo: repo.name,
                      path: contentResponse.data.path,
                      message: `ci: Adiciona arquivo de template '${contentResponse.data.name}'`,
                      content: contentResponse.data.content, // O conteúdo já vem em base64
                      branch: defaultBranch,
                    });
                  }
                } catch (error) {
                  if (error.status === 404) {
                     core.warning(`⚠️ Aviso: O caminho/arquivo "${path}" não foi encontrado no template e será ignorado.`);
                  } else {
                     core.warning(`⚠️ Aviso ao copiar "${path}": ${error.message}`);
                  }
                }
              };

              for (const path of pathsToCopy) {
                await copyContent(path);
              }
              log('✅ Cópia de arquivos do template finalizada.');

              // --- 3. CRIAR BRANCHES PADRÃO (develop, homolog) ---
              log("Criando branches padrão...");
              const mainRef = await github.rest.git.getRef({ owner: orgName, repo: repo.name, ref: `heads/${defaultBranch}` });
              const mainSha = mainRef.data.object.sha;

              const branchesToCreate = ["develop", "homolog"];
              for (const branchName of branchesToCreate) {
                await github.rest.git.createRef({ owner: orgName, repo: repo.name, ref: `refs/heads/${branchName}`, sha: mainSha });
                log(` -> Branch '${branchName}' criado.`);
              }

              // --- 4. ADICIONAR PERMISSÕES PARA TIMES ---
              log("Adicionando permissões para os times...");
              const teamsToAssign = [mainTeamSlug, 'techleads', 'devops', 'productionteam'];
              for (const teamSlug of [...new Set(teamsToAssign)]) {
                await github.rest.teams.addOrUpdateRepoPermissionsInOrg({ org: orgName, team_slug: teamSlug, owner: orgName, repo: repo.name, permission: 'push' });
                log(` -> Permissão de 'push' adicionada para "${teamSlug}".`);
              }

              // --- 5. APLICAR REGRAS DE PROTEÇÃO DE BRANCH ---
              log('Aplicando regras de proteção de branch...');
              const branchesToProtect = ["main", "develop", "homolog"];
              for (const branchName of branchesToProtect) {
                await github.rest.repos.updateBranchProtection({
                  owner: orgName,
                  repo: repo.name,
                  branch: branchName,
                  required_status_checks: null,
                  enforce_admins: true,
                  required_pull_request_reviews: { required_approving_review_count: 1 },
                  restrictions: null,
                });
                log(` -> Regra de proteção aplicada ao branch '${branchName}'.`);
              }

              log(`\n🎉 Processo concluído com sucesso!`);

            } catch (error) {
              if (error.status === 422 && error.message.includes("name already exists")) {
                core.setFailed(`❌ Erro: O repositório "${repoName}" já existe na organização "${orgName}".`);
              } else {
                core.setFailed(`❌ Erro crítico durante a execução: ${error.message}.`);
              }
            }
